name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        
    - name: docker vers
      run: |
        docker --version
        
    - name: make images
      run: |
        docker build -t test03 .
        docker images
    
    - name: save images
      run: |
        docker pull  fd383e7870f3
        docker save -0 anular.tar fd383e7870f3
