name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      
    - uses: actions/labeler@v2
      with:
       repo-token: ${{ secrets.GITHUB_TOKEN }}
          
    - name: docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        cd dist     
        
    - name: make images
      run: |
        docker build -t myang -f /home/runner/work/angular-react-starter/angular-react-starter/Dockerfile .
        docker images
        docker run myang  
