name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        cd dist
        ls
        pwd
        
        
        
    - name: make images
      run: |
        docker build -t myang -f /home/runner/work/angular-react-starter/angular-react-starter/Dockerfile .
        docker images
        docker run myang
        
  
    - name: Login to GitHub Container Registry
      run: |
        docker tag myang ghcr.io/darliiin/myang:latest
        docker images
        echo "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" | docker login ghcr.io -u darliiin --password-stdin
        docker push ghcr.io/darliiin/myang 
        
        
  
