name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        
        
    - name: make images
      run: |
        docker build -t ghcr.io .
        
    
    - name: save images
      run: |
        export CR_PAT=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
        docker login ghcr.io -u $darliiin -p $CR_PAT
        
        
  
