name: onetest
on:
  push:
    branches:
      -master
      
jobs:
  runtest: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
      - name: List cerretnt
        run: ls -la
      
      - name: starttest
        run: | 
          npm test
          npm coverage
