name: onetest

on: [push]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  one_test:
    runs-on: ubuntu-latest
    permissions:
     contents: read
     packages: write

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        cd dist     
        
    - name: make images
      run: |
        docker build -t myang -f /home/runner/work/angular-react-starter/angular-react-starter/Dockerfile .
  
    - name: Log in to the Container registry
      uses: docker/login-action@d34903b3ba81e2021319800b6cef18673e75fa5d
      with:
       registry: ${{ env.REGISTRY }}
       username: ${{ github.actor }}
       password: ${{ secrets.GITHUB_TOKEN }}
      
        
     
