name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1
      

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        cd dist     
        
    - name: make images
      run: |
        docker build -t myang -f /home/runner/work/angular-react-starter/angular-react-starter/Dockerfile .
        docker images
        docker run myang  
        
        
  build-and-push-image:
    runs-on: ubuntu-latest
    needs: one_test 
    permissions: 
      contents: read
      packages: write 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: docker.YOUR-HOSTNAME.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          push: true
          tags: |
            docker.YOUR-HOSTNAME.com/${{ github.repository }}/octo-image:${{ github.sha }}

