name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
             
        
    - name: START angular test
      run: |
        cd angular-react-starter
        cd angular
        npm install
  
    - name: build
      run: |
        cd angular-react-starter
        cd angular
        npm run ng build
        
        
    - name: Build the stack
      run: docker-compose -f docker-compose.prod.yml -f docker-compose.test.yml up -d --build
 
        


