name: onetest

on: [push]

jobs:
  one_test:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone my repo
      uses: actions/checkout@v1

    - name: Clone repo
      run: |
        git clone https://github.com/ganatan/angular-react-starter.git
        cd angular-react-starter
        cd angular
        npm install

    - name: START test
      run: |
        npm run coverage
      
