name: onetest
on:
  push:
    branches:
      -master
      
jobs:
  runtest: 
    runs-on: alpine
    
    steps:
      - name: Git clone my repo
        uses: actions/checkout@v1 
      
      - name: starttest
        run: | 
          npm run test
          npm run coverage
